language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
install:
  - pip install -q Django==$DJANGO_VERSION
script: python setup.py test
